
CREATE DATABASE BANCO;
USE BANCO;

CREATE TABLE CLIENTE (
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SEXO ENUM('M','F') NOT NULL
);

CREATE TABLE CONTA (
IDCONTA INT PRIMARY KEY AUTO_INCREMENT,
NUMERO_CONTA VARCHAR(10) NOT NULL,
AGENCIA INT(4) NOT NULL,
ID_CLIENTE INT
);

CREATE TABLE TRANSACOES (
IDTRANSACAO INT PRIMARY KEY AUTO_INCREMENT,
TRANSACAO INT NOT NULL,
TIPO ENUM('TED','DOC','PIX') NOT NULL,
ID_CLIENTE INT
);

/*CRIAÇÃO DE CONSTRAINT PARA FOREIGN KEY*/

ALTER TABLE CONTA ADD CONSTRAINT FK_CONTA_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE TRANSACOES ADD CONSTRAINT FK_TRANSACOES_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);


/* INSERÇÃO DE DADOS */

INSERT INTO CLIENTE VALUES (NULL,'BRUNO SILVA','M');
INSERT INTO CLIENTE VALUES (NULL,'ANDRE GARCIA','M');
INSERT INTO CLIENTE VALUES (NULL,'SILVA TAVARES','F');
INSERT INTO CLIENTE VALUES (NULL,'AMANDA GUERRA','F');
INSERT INTO CLIENTE VALUES (NULL,'PEDRO HENRIQUE','M');
INSERT INTO CLIENTE VALUES (NULL,'MARCOS AUGUSTO','M');
INSERT INTO CLIENTE VALUES (NULL,'MARCELA LEAO','F');

INSERT INTO CONTA VALUES (NULL,'25800-2','0777',1);
INSERT INTO CONTA VALUES (NULL,'22100-2','0777',4);
INSERT INTO CONTA VALUES (NULL,'13122-4','0632',2);
INSERT INTO CONTA VALUES (NULL,'17012-1','0421',5);
INSERT INTO CONTA VALUES (NULL,'17088-1','0421',3);
INSERT INTO CONTA VALUES (NULL,'14002-4','0632',7);
INSERT INTO CONTA VALUES (NULL,'26112-2','0315',6);

INSERT INTO TRANSACOES VALUES (NULL,1833,'TED',2);
INSERT INTO TRANSACOES VALUES (NULL,2750,'DOC',2);
INSERT INTO TRANSACOES VALUES (NULL,522,'TED',1);
INSERT INTO TRANSACOES VALUES (NULL,1213,'DOC',1);
INSERT INTO TRANSACOES VALUES (NULL,823,'DOC',3);
INSERT INTO TRANSACOES VALUES (NULL,423,'TED',4);
INSERT INTO TRANSACOES VALUES (NULL,1500,'TED',4);
INSERT INTO TRANSACOES VALUES (NULL,613,'TED',4);
INSERT INTO TRANSACOES VALUES (NULL,923,'DOC',5);
INSERT INTO TRANSACOES VALUES (NULL,513,'TED',6);
INSERT INTO TRANSACOES VALUES (NULL,1300,'TED',7);
INSERT INTO TRANSACOES VALUES (NULL,755,'DOC',5);
INSERT INTO TRANSACOES VALUES (NULL,300,'TED',6);

/* SELECT RELACIONANDO AS TABELAS*/

SELECT 
C.NOME,
C.SEXO,
O.NUMERO_CONTA,
O.AGENCIA,
T.TRANSACAO,
T.TIPO
FROM CLIENTE C
INNER JOIN CONTA O
ON C.IDCLIENTE = O.ID_CLIENTE
INNER JOIN TRANSACOES T
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY 1;
